#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: BP_UI_ControllerData_PS5

#include "Basic.hpp"

#include "GolfIt_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UI_ControllerData_PS5.BP_UI_ControllerData_PS5_C
// 0x0000 (0x00B0 - 0x00B0)
class UBP_UI_ControllerData_PS5_C final : public UGolfItInputBaseControllerData
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_UI_ControllerData_PS5_C">();
	}
	static class UBP_UI_ControllerData_PS5_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UI_ControllerData_PS5_C>();
	}
};

}

