#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: E_TerrainType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_TerrainType.E_TerrainType
// NumValues: 0x0004
enum class E_TerrainType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	E_MAX                                    = 3,
};

}

