#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: Force_Field

#include "Basic.hpp"

#include "Force_Field_classes.hpp"
#include "Force_Field_parameters.hpp"


namespace SDK
{

// Function Force_Field.Force_Field_C.ExecuteUbergraph_Force_Field
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AForce_Field_C::ExecuteUbergraph_Force_Field(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "ExecuteUbergraph_Force_Field");

	Params::Force_Field_C_ExecuteUbergraph_Force_Field Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Force_Field.Force_Field_C.ReceiveActorEndOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AForce_Field_C::ReceiveActorEndOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "ReceiveActorEndOverlap");

	Params::Force_Field_C_ReceiveActorEndOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Force_Field.Force_Field_C.ChangeVisibility
// (BlueprintCallable, BlueprintEvent)

void AForce_Field_C::ChangeVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "ChangeVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Force_Field.Force_Field_C.NewVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visibility                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AForce_Field_C::NewVisibility(bool Visibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "NewVisibility");

	Params::Force_Field_C_NewVisibility Parms{};

	Parms.Visibility = Visibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Force_Field.Force_Field_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AForce_Field_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "ReceiveActorBeginOverlap");

	Params::Force_Field_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Force_Field.Force_Field_C.ActivateForce
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewActivation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AForce_Field_C::ActivateForce(bool NewActivation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "ActivateForce");

	Params::Force_Field_C_ActivateForce Parms{};

	Parms.NewActivation = NewActivation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Force_Field.Force_Field_C.NewForce
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AForce_Field_C::NewForce(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "NewForce");

	Params::Force_Field_C_NewForce Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Force_Field.Force_Field_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AForce_Field_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Force_Field.Force_Field_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AForce_Field_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "ReceiveTick");

	Params::Force_Field_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Force_Field.Force_Field_C.Resize
// (Public, BlueprintCallable, BlueprintEvent)

void AForce_Field_C::Resize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "Resize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Force_Field.Force_Field_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AForce_Field_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Force_Field.Force_Field_C.GetForce
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AForce_Field_C::GetForce(float* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Force_Field_C", "GetForce");

	Params::Force_Field_C_GetForce Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = Parms.Value;
}

}

