#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: GolfItDataHub

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


namespace SDK
{

// Enum GolfItDataHub.EDataHubGetDataResult
// NumValues: 0x0006
enum class EDataHubGetDataResult : uint8
{
	Success                                  = 0,
	NotActive                                = 1,
	NoValue                                  = 2,
	WrongType                                = 3,
	InvalidHandle                            = 4,
	EDataHubGetDataResult_MAX                = 5,
};

// ScriptStruct GolfItDataHub.DataHubHandle
// 0x000C (0x000C - 0x0000)
struct FDataHubHandle final
{
public:
	struct FGameplayTag                           MGameplayTag;                                      // 0x0000(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8[0x4];                                        // 0x0008(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

}

