#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: LoadCustomLevelActor

#include "Basic.hpp"

#include "LoadCustomLevelActor_classes.hpp"
#include "LoadCustomLevelActor_parameters.hpp"


namespace SDK
{

// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_Camera
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Camera(class ASimpleEditorActor_C* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_Camera");

	Params::LoadCustomLevelActor_C_Setup_Camera Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SaveEventsToCheckAndRemoveDuplicates
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AStaticEventActor_C*              NewItem                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SaveEventsToCheckAndRemoveDuplicates(const class AStaticEventActor_C*& NewItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SaveEventsToCheckAndRemoveDuplicates");

	Params::LoadCustomLevelActor_C_SaveEventsToCheckAndRemoveDuplicates Parms{};

	Parms.NewItem = NewItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_Waterfall
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Waterfall(class ASimpleEditorActor_C* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_Waterfall");

	Params::LoadCustomLevelActor_C_Setup_Waterfall Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SettingMusik
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Completed                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALoadCustomLevelActor_C::SettingMusik(bool* Completed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SettingMusik");

	Params::LoadCustomLevelActor_C_SettingMusik Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Completed != nullptr)
		*Completed = Parms.Completed;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SetupGoalSettings
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FS_AdditionalObjectInfo_Master   S_AdditionalObjectInfo_Master                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// class ASimpleEditorActor_C*             CurrentSpawnActor                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SetupGoalSettings(const struct FS_AdditionalObjectInfo_Master& S_AdditionalObjectInfo_Master, class ASimpleEditorActor_C* CurrentSpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SetupGoalSettings");

	Params::LoadCustomLevelActor_C_SetupGoalSettings Parms{};

	Parms.S_AdditionalObjectInfo_Master = std::move(S_AdditionalObjectInfo_Master);
	Parms.CurrentSpawnActor = CurrentSpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_Magnet
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Magnet(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_Magnet");

	Params::LoadCustomLevelActor_C_Setup_Magnet Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.StartObjectFunctions
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::StartObjectFunctions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "StartObjectFunctions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.CreateVoxelInvoker
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::CreateVoxelInvoker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "CreateVoxelInvoker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_MasterLight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_MasterLight(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_MasterLight");

	Params::LoadCustomLevelActor_C_Setup_MasterLight Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.ApplyMaterialProperties
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         Material                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FS_CustomMaterial_Optimized      MaterialProperties                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::ApplyMaterialProperties(class UMaterialInstanceDynamic* Material, const struct FS_CustomMaterial_Optimized& MaterialProperties)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "ApplyMaterialProperties");

	Params::LoadCustomLevelActor_C_ApplyMaterialProperties Parms{};

	Parms.Material = Material;
	Parms.MaterialProperties = std::move(MaterialProperties);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.GetAndLoadTextures
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACustomMapWorldSettings_C*        Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Diffuse                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Normal                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ArrayIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture2D*                       LocalDiffuse1                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture2D*                       LocalNormal1                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::GetAndLoadTextures(class ACustomMapWorldSettings_C* Target, int32 Diffuse, int32 Normal, int32 Param_Index, int32 ArrayIndex, class UTexture2D** LocalDiffuse1, class UTexture2D** LocalNormal1)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "GetAndLoadTextures");

	Params::LoadCustomLevelActor_C_GetAndLoadTextures Parms{};

	Parms.Target = Target;
	Parms.Diffuse = Diffuse;
	Parms.Normal = Normal;
	Parms.Param_Index = Param_Index;
	Parms.ArrayIndex = ArrayIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (LocalDiffuse1 != nullptr)
		*LocalDiffuse1 = Parms.LocalDiffuse1;

	if (LocalNormal1 != nullptr)
		*LocalNormal1 = Parms.LocalNormal1;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.GetDefaultMaterial
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Param_Name                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UMaterialInstanceDynamic*         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UMaterialInstanceDynamic* ALoadCustomLevelActor_C::GetDefaultMaterial(const class FString& Param_Name)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "GetDefaultMaterial");

	Params::LoadCustomLevelActor_C_GetDefaultMaterial Parms{};

	Parms.Param_Name = std::move(Param_Name);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.GenerateBaseMaterial
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Translucent                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Alpha                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UMaterialInstanceDynamic*         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UMaterialInstanceDynamic* ALoadCustomLevelActor_C::GenerateBaseMaterial(bool Translucent, bool Alpha)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "GenerateBaseMaterial");

	Params::LoadCustomLevelActor_C_GenerateBaseMaterial Parms{};

	Parms.Translucent = Translucent;
	Parms.Alpha = Alpha;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.CreateMaterial
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACustomMapWorldSettings_C*        Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FS_CustomMaterial_Optimized      MaterialProperties                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ArrayIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UMaterialInstanceDynamic*         Material                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::CreateMaterial(class ACustomMapWorldSettings_C* Target, const struct FS_CustomMaterial_Optimized& MaterialProperties, int32 Param_Index, int32 ArrayIndex, class UMaterialInstanceDynamic** Material)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "CreateMaterial");

	Params::LoadCustomLevelActor_C_CreateMaterial Parms{};

	Parms.Target = Target;
	Parms.MaterialProperties = std::move(MaterialProperties);
	Parms.Param_Index = Param_Index;
	Parms.ArrayIndex = ArrayIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (Material != nullptr)
		*Material = Parms.Material;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.CreateStaticMeshFromDynamicMeshData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FImportedObjTransforms           ImportedObjTransforms                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// int32                                   Current_Index                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PoolIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::CreateStaticMeshFromDynamicMeshData(const struct FImportedObjTransforms& ImportedObjTransforms, int32 Current_Index, int32 PoolIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "CreateStaticMeshFromDynamicMeshData");

	Params::LoadCustomLevelActor_C_CreateStaticMeshFromDynamicMeshData Parms{};

	Parms.ImportedObjTransforms = std::move(ImportedObjTransforms);
	Parms.Current_Index = Current_Index;
	Parms.PoolIndex = PoolIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_Water
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Water(class ASimpleEditorActor_C* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_Water");

	Params::LoadCustomLevelActor_C_Setup_Water Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_UnderwaterObjects
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_UnderwaterObjects(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_UnderwaterObjects");

	Params::LoadCustomLevelActor_C_Setup_UnderwaterObjects Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SelectLevelThemeForEditor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCustomLevel_C*                   CustomLevel                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           ThemeName                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SelectLevelThemeForEditor(class UCustomLevel_C* CustomLevel, class FString* ThemeName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SelectLevelThemeForEditor");

	Params::LoadCustomLevelActor_C_SelectLevelThemeForEditor Parms{};

	Parms.CustomLevel = CustomLevel;

	UObject::ProcessEvent(Func, &Parms);

	if (ThemeName != nullptr)
		*ThemeName = std::move(Parms.ThemeName);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.PreGatherAdditionalLoadingLengths
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::PreGatherAdditionalLoadingLengths()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "PreGatherAdditionalLoadingLengths");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.GetAndSetSecondaryLength
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::GetAndSetSecondaryLength()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "GetAndSetSecondaryLength");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SpawnSecondaryInstances
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Completed                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALoadCustomLevelActor_C::SpawnSecondaryInstances(bool* Completed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SpawnSecondaryInstances");

	Params::LoadCustomLevelActor_C_SpawnSecondaryInstances Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Completed != nullptr)
		*Completed = Parms.Completed;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.ServerSpawnFlyTraps
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::ServerSpawnFlyTraps()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "ServerSpawnFlyTraps");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Set Info In Mesh
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ADynamicMesh_C*                   Mesh                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Set_Info_In_Mesh(class ADynamicMesh_C* Mesh, int32 Param_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Set Info In Mesh");

	Params::LoadCustomLevelActor_C_Set_Info_In_Mesh Parms{};

	Parms.Mesh = Mesh;
	Parms.Param_Index = Param_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SortAssetData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::SortAssetData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SortAssetData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.ChangeLoadStatus
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_MapLoad                            NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// Enum_MapLoad                            ReturnState                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::ChangeLoadStatus(Enum_MapLoad NewState, Enum_MapLoad* ReturnState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "ChangeLoadStatus");

	Params::LoadCustomLevelActor_C_ChangeLoadStatus Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);

	if (ReturnState != nullptr)
		*ReturnState = Parms.ReturnState;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.RemoveLoadingWidget
// (Public, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::RemoveLoadingWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "RemoveLoadingWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.CreateLoadingWidget
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::CreateLoadingWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "CreateLoadingWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SettingFinal
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::SettingFinal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SettingFinal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.GetAndSetSpecialSpawnPosition
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    VR                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FTransform                       PlayerStart                                            (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FTransform                       VRTransform                                            (Parm, OutParm, IsPlainOldData, NoDestructor)

void ALoadCustomLevelActor_C::GetAndSetSpecialSpawnPosition(bool VR, const struct FTransform& PlayerStart, struct FTransform* VRTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "GetAndSetSpecialSpawnPosition");

	Params::LoadCustomLevelActor_C_GetAndSetSpecialSpawnPosition Parms{};

	Parms.VR = VR;
	Parms.PlayerStart = std::move(PlayerStart);

	UObject::ProcessEvent(Func, &Parms);

	if (VRTransform != nullptr)
		*VRTransform = std::move(Parms.VRTransform);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.ResolveEventIDs
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::ResolveEventIDs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "ResolveEventIDs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SettingAudio
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Completed                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALoadCustomLevelActor_C::SettingAudio(bool* Completed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SettingAudio");

	Params::LoadCustomLevelActor_C_SettingAudio Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Completed != nullptr)
		*Completed = Parms.Completed;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.DetermineIfTerrainDeleted
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCustomLevel_C*                   MapRef                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::DetermineIfTerrainDeleted(class UCustomLevel_C* MapRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "DetermineIfTerrainDeleted");

	Params::LoadCustomLevelActor_C_DetermineIfTerrainDeleted Parms{};

	Parms.MapRef = MapRef;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.DestroyVoxelWorld
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::DestroyVoxelWorld()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "DestroyVoxelWorld");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SetMeshInstances
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MaxLength                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SetMeshInstances(int32 MaxLength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SetMeshInstances");

	Params::LoadCustomLevelActor_C_SetMeshInstances Parms{};

	Parms.MaxLength = MaxLength;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SetUniqueIds
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::SetUniqueIds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SetUniqueIds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SetDynamicMesh
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MaxLength                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SetDynamicMesh(int32 MaxLength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SetDynamicMesh");

	Params::LoadCustomLevelActor_C_SetDynamicMesh Parms{};

	Parms.MaxLength = MaxLength;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SpawnDynamicMesh
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ADynamicMesh_C*                   Ref                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SpawnDynamicMesh(int32 Param_Index, class ADynamicMesh_C** Ref)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SpawnDynamicMesh");

	Params::LoadCustomLevelActor_C_SpawnDynamicMesh Parms{};

	Parms.Param_Index = Param_Index;

	UObject::ProcessEvent(Func, &Parms);

	if (Ref != nullptr)
		*Ref = Parms.Ref;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.DisplayLoadingScreenIfVR
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       LoadingTexture                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::DisplayLoadingScreenIfVR(class UTexture2D* LoadingTexture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "DisplayLoadingScreenIfVR");

	Params::LoadCustomLevelActor_C_DisplayLoadingScreenIfVR Parms{};

	Parms.LoadingTexture = LoadingTexture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SetSpecialSettings
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    UseDispatch                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALoadCustomLevelActor_C::SetSpecialSettings(bool* UseDispatch)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SetSpecialSettings");

	Params::LoadCustomLevelActor_C_SetSpecialSettings Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (UseDispatch != nullptr)
		*UseDispatch = Parms.UseDispatch;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SpawnEventObjects
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::SpawnEventObjects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SpawnEventObjects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SetDynamicLanes
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   BatchSize                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   MaxLength                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SetDynamicLanes(int32 Param_Index, int32 BatchSize, int32 MaxLength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SetDynamicLanes");

	Params::LoadCustomLevelActor_C_SetDynamicLanes Parms{};

	Parms.Param_Index = Param_Index;
	Parms.BatchSize = BatchSize;
	Parms.MaxLength = MaxLength;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SpawnDynamicLanes
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FDynamicSplineStruct             DynamicStruct                                          (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ADynamicLaneBP_C*                 Ref                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SpawnDynamicLanes(const struct FDynamicSplineStruct& DynamicStruct, class ADynamicLaneBP_C** Ref)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SpawnDynamicLanes");

	Params::LoadCustomLevelActor_C_SpawnDynamicLanes Parms{};

	Parms.DynamicStruct = std::move(DynamicStruct);

	UObject::ProcessEvent(Func, &Parms);

	if (Ref != nullptr)
		*Ref = Parms.Ref;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SetPostProcess
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::SetPostProcess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SetPostProcess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SpawnPostProcessVolumes
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPostProcess_Struct              PostProcessStruct                                      (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SpawnPostProcessVolumes(const struct FPostProcess_Struct& PostProcessStruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SpawnPostProcessVolumes");

	Params::LoadCustomLevelActor_C_SpawnPostProcessVolumes Parms{};

	Parms.PostProcessStruct = std::move(PostProcessStruct);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Set Rotational
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UStaticMesh*>              RotationalMeshes                                       (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FTransform>               RotationalTransform                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FRotator>                 RotationalStart                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FRotator>                 RotationalEnd                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FVector>                  RotationalSpeeds                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ALoadCustomLevelActor_C::Set_Rotational(TArray<class UStaticMesh*>& RotationalMeshes, const TArray<struct FTransform>& RotationalTransform, const TArray<struct FRotator>& RotationalStart, const TArray<struct FRotator>& RotationalEnd, const TArray<struct FVector>& RotationalSpeeds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Set Rotational");

	Params::LoadCustomLevelActor_C_Set_Rotational Parms{};

	Parms.RotationalMeshes = std::move(RotationalMeshes);
	Parms.RotationalTransform = std::move(RotationalTransform);
	Parms.RotationalStart = std::move(RotationalStart);
	Parms.RotationalEnd = std::move(RotationalEnd);
	Parms.RotationalSpeeds = std::move(RotationalSpeeds);

	UObject::ProcessEvent(Func, &Parms);

	RotationalMeshes = std::move(Parms.RotationalMeshes);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SetRotators
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UStaticMesh*>              RotatorMeshes                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FTransform>               RotatorTransform                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FVector>                  RotatorSpeed                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<E_Editor_Themes>                 RotatorCategory                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<int32>                           RotatorID                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FVector>                  RotatorOffset                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FS_AdditionalObjectInfo_Master>RotatorAdditional                                      (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ALoadCustomLevelActor_C::SetRotators(TArray<class UStaticMesh*>& RotatorMeshes, const TArray<struct FTransform>& RotatorTransform, const TArray<struct FVector>& RotatorSpeed, const TArray<E_Editor_Themes>& RotatorCategory, const TArray<int32>& RotatorID, const TArray<struct FVector>& RotatorOffset, TArray<struct FS_AdditionalObjectInfo_Master>& RotatorAdditional)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SetRotators");

	Params::LoadCustomLevelActor_C_SetRotators Parms{};

	Parms.RotatorMeshes = std::move(RotatorMeshes);
	Parms.RotatorTransform = std::move(RotatorTransform);
	Parms.RotatorSpeed = std::move(RotatorSpeed);
	Parms.RotatorCategory = std::move(RotatorCategory);
	Parms.RotatorID = std::move(RotatorID);
	Parms.RotatorOffset = std::move(RotatorOffset);
	Parms.RotatorAdditional = std::move(RotatorAdditional);

	UObject::ProcessEvent(Func, &Parms);

	RotatorMeshes = std::move(Parms.RotatorMeshes);
	RotatorAdditional = std::move(Parms.RotatorAdditional);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.CheckToNotBe0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          ScaleIn                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          OutScale                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::CheckToNotBe0(const struct FVector& ScaleIn, struct FVector* OutScale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "CheckToNotBe0");

	Params::LoadCustomLevelActor_C_CheckToNotBe0 Parms{};

	Parms.ScaleIn = std::move(ScaleIn);

	UObject::ProcessEvent(Func, &Parms);

	if (OutScale != nullptr)
		*OutScale = std::move(Parms.OutScale);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SetSky
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Time_of_Day                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   SunAngle                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SetSky(float Time_of_Day, float SunAngle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SetSky");

	Params::LoadCustomLevelActor_C_SetSky Parms{};

	Parms.Time_of_Day = Time_of_Day;
	Parms.SunAngle = SunAngle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Get and Set Special Spawn Position
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    VR                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FTransform                       PlayerStart                                            (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FTransform                       VRTransform                                            (Parm, OutParm, IsPlainOldData, NoDestructor)

void ALoadCustomLevelActor_C::Get_and_Set_Special_Spawn_Position(bool VR, const struct FTransform& PlayerStart, struct FTransform* VRTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Get and Set Special Spawn Position");

	Params::LoadCustomLevelActor_C_Get_and_Set_Special_Spawn_Position Parms{};

	Parms.VR = VR;
	Parms.PlayerStart = std::move(PlayerStart);

	UObject::ProcessEvent(Func, &Parms);

	if (VRTransform != nullptr)
		*VRTransform = std::move(Parms.VRTransform);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.SingleObjectBatchLoad
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MaxLength                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::SingleObjectBatchLoad(int32 MaxLength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "SingleObjectBatchLoad");

	Params::LoadCustomLevelActor_C_SingleObjectBatchLoad Parms{};

	Parms.MaxLength = MaxLength;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.UpdateLoadingScreenText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             NewText                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void ALoadCustomLevelActor_C::UpdateLoadingScreenText(const class FText& NewText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "UpdateLoadingScreenText");

	Params::LoadCustomLevelActor_C_UpdateLoadingScreenText Parms{};

	Parms.NewText = std::move(NewText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Generate Custom Materials
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::Generate_Custom_Materials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Generate Custom Materials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_SocketAndDefault
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_SocketAndDefault(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_SocketAndDefault");

	Params::LoadCustomLevelActor_C_Setup_SocketAndDefault Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_River
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_River(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_River");

	Params::LoadCustomLevelActor_C_Setup_River Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_AudioActor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_AudioActor(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_AudioActor");

	Params::LoadCustomLevelActor_C_Setup_AudioActor Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_Planets
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Planets(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_Planets");

	Params::LoadCustomLevelActor_C_Setup_Planets Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_GravityField
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_GravityField(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_GravityField");

	Params::LoadCustomLevelActor_C_Setup_GravityField Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_GravitySphere
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_GravitySphere(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_GravitySphere");

	Params::LoadCustomLevelActor_C_Setup_GravitySphere Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_ForceField
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             InputPin                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_ForceField(class ASimpleEditorActor_C* InputPin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_ForceField");

	Params::LoadCustomLevelActor_C_Setup_ForceField Parms{};

	Parms.InputPin = InputPin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_ForceSphere
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             InputPin                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_ForceSphere(class ASimpleEditorActor_C* InputPin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_ForceSphere");

	Params::LoadCustomLevelActor_C_Setup_ForceSphere Parms{};

	Parms.InputPin = InputPin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.MarkToDelete_Simple
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SpawnActor                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::MarkToDelete_Simple(const class AActor*& SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "MarkToDelete_Simple");

	Params::LoadCustomLevelActor_C_MarkToDelete_Simple Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_Text
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Text(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_Text");

	Params::LoadCustomLevelActor_C_Setup_Text Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_Transformer
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Transformer(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_Transformer");

	Params::LoadCustomLevelActor_C_Setup_Transformer Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup Rotational
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Rotational(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup Rotational");

	Params::LoadCustomLevelActor_C_Setup_Rotational Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_Canon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Canon(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_Canon");

	Params::LoadCustomLevelActor_C_Setup_Canon Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Seup_ResetArea
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Seup_ResetArea(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Seup_ResetArea");

	Params::LoadCustomLevelActor_C_Seup_ResetArea Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_Teleporter
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             InputPin                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Teleporter(class ASimpleEditorActor_C* InputPin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_Teleporter");

	Params::LoadCustomLevelActor_C_Setup_Teleporter Parms{};

	Parms.InputPin = InputPin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup Rotator
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Rotator(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup Rotator");

	Params::LoadCustomLevelActor_C_Setup_Rotator Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_Boost
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_Boost(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_Boost");

	Params::LoadCustomLevelActor_C_Setup_Boost Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_PlayArea
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             SpawnActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_PlayArea(class ASimpleEditorActor_C* SpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_PlayArea");

	Params::LoadCustomLevelActor_C_Setup_PlayArea Parms{};

	Parms.SpawnActor = SpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Setup_HoleSpawn
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASimpleEditorActor_C*             CurrentSpawnActor                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::Setup_HoleSpawn(class ASimpleEditorActor_C* CurrentSpawnActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Setup_HoleSpawn");

	Params::LoadCustomLevelActor_C_Setup_HoleSpawn Parms{};

	Parms.CurrentSpawnActor = CurrentSpawnActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.LoadSingleObject
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UStaticMesh*                      Mesh                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsClient                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALoadCustomLevelActor_C::LoadSingleObject(class UStaticMesh* Mesh, bool IsClient)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "LoadSingleObject");

	Params::LoadCustomLevelActor_C_LoadSingleObject Parms{};

	Parms.Mesh = Mesh;
	Parms.IsClient = IsClient;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "ReceiveTick");

	Params::LoadCustomLevelActor_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.OnBeginLoadMap
// (Event, Protected, BlueprintEvent)

void ALoadCustomLevelActor_C::OnBeginLoadMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "OnBeginLoadMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.RegisteredEventsForIDChecks
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AStaticEventActor_C*              NewEventActor                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::RegisteredEventsForIDChecks(class AStaticEventActor_C* NewEventActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "RegisteredEventsForIDChecks");

	Params::LoadCustomLevelActor_C_RegisteredEventsForIDChecks Parms{};

	Parms.NewEventActor = NewEventActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.BindIDRegistry
// (BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::BindIDRegistry()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "BindIDRegistry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.CustomTexturePoolDoneGenerating
// (BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::CustomTexturePoolDoneGenerating()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "CustomTexturePoolDoneGenerating");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.UpdatingCustomTexturePoolText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CurrentIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   LastIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::UpdatingCustomTexturePoolText(int32 CurrentIndex, int32 LastIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "UpdatingCustomTexturePoolText");

	Params::LoadCustomLevelActor_C_UpdatingCustomTexturePoolText Parms{};

	Parms.CurrentIndex = CurrentIndex;
	Parms.LastIndex = LastIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ALoadCustomLevelActor_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.ExecuteUbergraph_LoadCustomLevelActor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::ExecuteUbergraph_LoadCustomLevelActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "ExecuteUbergraph_LoadCustomLevelActor");

	Params::LoadCustomLevelActor_C_ExecuteUbergraph_LoadCustomLevelActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.LevelLoadComplete__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void ALoadCustomLevelActor_C::LevelLoadComplete__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "LevelLoadComplete__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.Check Visibility
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FS_AdditionalObjectInfo_Master>Array                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Found                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Value                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALoadCustomLevelActor_C::Check_Visibility(TArray<struct FS_AdditionalObjectInfo_Master>& Array, int32 Param_Index, bool* Found, bool* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "Check Visibility");

	Params::LoadCustomLevelActor_C_Check_Visibility Parms{};

	Parms.Array = std::move(Array);
	Parms.Param_Index = Param_Index;

	UObject::ProcessEvent(Func, &Parms);

	Array = std::move(Parms.Array);

	if (Found != nullptr)
		*Found = Parms.Found;

	if (Value != nullptr)
		*Value = Parms.Value;
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.CheckLowestPoint
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTransform                       Transform                                              (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)

void ALoadCustomLevelActor_C::CheckLowestPoint(const struct FTransform& Transform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "CheckLowestPoint");

	Params::LoadCustomLevelActor_C_CheckLowestPoint Parms{};

	Parms.Transform = std::move(Transform);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoadCustomLevelActor.LoadCustomLevelActor_C.mOnDone_7A11516C4C2209D4A2F810A75BADE278
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Context                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USaveGame*                        SaveGame                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALoadCustomLevelActor_C::MOnDone_7A11516C4C2209D4A2F810A75BADE278(class UObject* Context, class USaveGame* SaveGame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LoadCustomLevelActor_C", "mOnDone_7A11516C4C2209D4A2F810A75BADE278");

	Params::LoadCustomLevelActor_C_MOnDone_7A11516C4C2209D4A2F810A75BADE278 Parms{};

	Parms.Context = Context;
	Parms.SaveGame = SaveGame;

	UObject::ProcessEvent(Func, &Parms);
}

}

