#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: S_Billiard_Combinations

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// UserDefinedStruct S_Billiard_Combinations.S_Billiard_Combinations
// 0x0040 (0x0040 - 0x0000)
struct FS_Billiard_Combinations final
{
public:
	struct FLinearColor                           Color_2_2296FA0E43C23AA02FB4DDA1C4DAB1E2;          // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              NumberTexture_9_283AFB3C497723A7763E779E516756A7;  // 0x0010(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          HighNumber_8_FC8A821D45C4D15C456F989E86ADDC85;     // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

