#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: TimeLimit

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct TimeLimit.TimeLimit
// 0x0010 (0x0010 - 0x0000)
struct FTimeLimit final
{
public:
	class FString                                 TimeLimits_2_D28A62B64802682DC63A3AA666592FD9;     // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};

}

