#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: VisibilityMeshesStruct

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct VisibilityMeshesStruct.VisibilityMeshesStruct
// 0x0050 (0x0050 - 0x0000)
struct FVisibilityMeshesStruct final
{
public:
	TSoftObjectPtr<class UStaticMesh>             Original_5_761EF1724CB531F6828379AA2AAA1820;       // 0x0000(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftObjectPtr<class UStaticMesh>             Visibility_6_D0FBE6C346AE31C807EDF69EEE3AABE7;     // 0x0028(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
};

}

