#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: WB_Button_Scoreboard

#include "Basic.hpp"

#include "WB_Button_Scoreboard_classes.hpp"
#include "WB_Button_Scoreboard_parameters.hpp"


namespace SDK
{

// Function WB_Button_Scoreboard.WB_Button_Scoreboard_C.SetupAdditionalIcons
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Button_Scoreboard_C::SetupAdditionalIcons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Button_Scoreboard_C", "SetupAdditionalIcons");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Button_Scoreboard.WB_Button_Scoreboard_C.SetAvatar
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       Texture                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Button_Scoreboard_C::SetAvatar(class UTexture2D* Texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Button_Scoreboard_C", "SetAvatar");

	Params::WB_Button_Scoreboard_C_SetAvatar Parms{};

	Parms.Texture = Texture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Button_Scoreboard.WB_Button_Scoreboard_C.SetName
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UWB_Button_Scoreboard_C::SetName(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Button_Scoreboard_C", "SetName");

	Params::WB_Button_Scoreboard_C_SetName Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Button_Scoreboard.WB_Button_Scoreboard_C.SetPlace
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Place                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Button_Scoreboard_C::SetPlace(int32 Place)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Button_Scoreboard_C", "SetPlace");

	Params::WB_Button_Scoreboard_C_SetPlace Parms{};

	Parms.Place = Place;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Button_Scoreboard.WB_Button_Scoreboard_C.SetRank
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Rank                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Button_Scoreboard_C::SetRank(int32 Rank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Button_Scoreboard_C", "SetRank");

	Params::WB_Button_Scoreboard_C_SetRank Parms{};

	Parms.Rank = Rank;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Button_Scoreboard.WB_Button_Scoreboard_C.SetIsVR
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ISVR                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Button_Scoreboard_C::SetIsVR(bool ISVR)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Button_Scoreboard_C", "SetIsVR");

	Params::WB_Button_Scoreboard_C_SetIsVR Parms{};

	Parms.ISVR = ISVR;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Button_Scoreboard.WB_Button_Scoreboard_C.SetIsVIP
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsVIP                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Button_Scoreboard_C::SetIsVIP(bool IsVIP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Button_Scoreboard_C", "SetIsVIP");

	Params::WB_Button_Scoreboard_C_SetIsVIP Parms{};

	Parms.IsVIP = IsVIP;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Button_Scoreboard.WB_Button_Scoreboard_C.SetIsHost
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHost                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Button_Scoreboard_C::SetIsHost(bool IsHost)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Button_Scoreboard_C", "SetIsHost");

	Params::WB_Button_Scoreboard_C_SetIsHost Parms{};

	Parms.IsHost = IsHost;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Button_Scoreboard.WB_Button_Scoreboard_C.SetIsGamepad
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsGamepad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Button_Scoreboard_C::SetIsGamepad(bool IsGamepad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Button_Scoreboard_C", "SetIsGamepad");

	Params::WB_Button_Scoreboard_C_SetIsGamepad Parms{};

	Parms.IsGamepad = IsGamepad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Button_Scoreboard.WB_Button_Scoreboard_C.ExecuteUbergraph_WB_Button_Scoreboard
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Button_Scoreboard_C::ExecuteUbergraph_WB_Button_Scoreboard(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Button_Scoreboard_C", "ExecuteUbergraph_WB_Button_Scoreboard");

	Params::WB_Button_Scoreboard_C_ExecuteUbergraph_WB_Button_Scoreboard Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

