#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: WB_HUD_Ingame

#include "Basic.hpp"

#include "WB_HUD_Ingame_classes.hpp"
#include "WB_HUD_Ingame_parameters.hpp"


namespace SDK
{

// Function WB_HUD_Ingame.WB_HUD_Ingame_C.ChangeViewMode
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGolfItLobbyPlayerState*          PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_Ingame_C::ChangeViewMode(class AGolfItLobbyPlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "ChangeViewMode");

	Params::WB_HUD_Ingame_C_ChangeViewMode Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD_Ingame.WB_HUD_Ingame_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWB_HUD_Ingame_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD_Ingame.WB_HUD_Ingame_C.ChangeRaceTimerVisibility
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_HUD_Ingame_C::ChangeRaceTimerVisibility(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "ChangeRaceTimerVisibility");

	Params::WB_HUD_Ingame_C_ChangeRaceTimerVisibility Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD_Ingame.WB_HUD_Ingame_C.OnInputTypeChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// ECommonInputType                        NewInputType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_Ingame_C::OnInputTypeChanged(ECommonInputType NewInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "OnInputTypeChanged");

	Params::WB_HUD_Ingame_C_OnInputTypeChanged Parms{};

	Parms.NewInputType = NewInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD_Ingame.WB_HUD_Ingame_C.ShowParText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ParDiff                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsInOne                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_HUD_Ingame_C::ShowParText(int32 ParDiff, bool IsInOne)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "ShowParText");

	Params::WB_HUD_Ingame_C_ShowParText Parms{};

	Parms.ParDiff = ParDiff;
	Parms.IsInOne = IsInOne;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD_Ingame.WB_HUD_Ingame_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_HUD_Ingame_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD_Ingame.WB_HUD_Ingame_C.PlayOptionsChanged
// (BlueprintCallable, BlueprintEvent)

void UWB_HUD_Ingame_C::PlayOptionsChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "PlayOptionsChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_HUD_Ingame.WB_HUD_Ingame_C.OnLayoutUpdated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActivatableWidgetContainerBase*Container                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag                     Layer                                                  (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class UCommonActivatableWidget*         Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_Ingame_C::OnLayoutUpdated(class UCommonActivatableWidgetContainerBase* Container, const struct FGameplayTag& Layer, class UCommonActivatableWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "OnLayoutUpdated");

	Params::WB_HUD_Ingame_C_OnLayoutUpdated Parms{};

	Parms.Container = Container;
	Parms.Layer = std::move(Layer);
	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD_Ingame.WB_HUD_Ingame_C.SetChallengeVisiblity
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    SetVisible                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_HUD_Ingame_C::SetChallengeVisiblity(bool SetVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "SetChallengeVisiblity");

	Params::WB_HUD_Ingame_C_SetChallengeVisiblity Parms{};

	Parms.SetVisible = SetVisible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD_Ingame.WB_HUD_Ingame_C.ExecuteUbergraph_WB_HUD_Ingame
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_HUD_Ingame_C::ExecuteUbergraph_WB_HUD_Ingame(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "ExecuteUbergraph_WB_HUD_Ingame");

	Params::WB_HUD_Ingame_C_ExecuteUbergraph_WB_HUD_Ingame Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_HUD_Ingame.WB_HUD_Ingame_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWB_HUD_Ingame_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_HUD_Ingame_C", "BP_GetDesiredFocusTarget");

	Params::WB_HUD_Ingame_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

