#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: WB_Lobby

#include "Basic.hpp"

#include "WB_Lobby_classes.hpp"
#include "WB_Lobby_parameters.hpp"


namespace SDK
{

// Function WB_Lobby.WB_Lobby_C.ExecuteUbergraph_WB_Lobby
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::ExecuteUbergraph_WB_Lobby(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "ExecuteUbergraph_WB_Lobby");

	Params::WB_Lobby_C_ExecuteUbergraph_WB_Lobby Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_MidRoundScoring_K2Node_ComponentBoundEvent_3_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_MidRoundScoring_K2Node_ComponentBoundEvent_3_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_MidRoundScoring_K2Node_ComponentBoundEvent_3_OnSelectionChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_MidRoundScoring_K2Node_ComponentBoundEvent_3_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_AllowJoinMidRound_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_AllowJoinMidRound_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_AllowJoinMidRound_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_AllowJoinMidRound_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Button_ToggleServerOpen_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Button_ToggleServerOpen_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Button_ToggleServerOpen_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Button_ToggleServerOpen_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_HotseatPlayOrder_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_HotseatPlayOrder_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_HotseatPlayOrder_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_HotseatPlayOrder_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.InputAction_NotReady
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ActionName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::InputAction_NotReady(class FName ActionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "InputAction_NotReady");

	Params::WB_Lobby_C_InputAction_NotReady Parms{};

	Parms.ActionName = ActionName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.InputAction_Ready
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ActionName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::InputAction_Ready(class FName ActionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "InputAction_Ready");

	Params::WB_Lobby_C_InputAction_Ready Parms{};

	Parms.ActionName = ActionName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.InputAction_Start
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ActionName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::InputAction_Start(class FName ActionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "InputAction_Start");

	Params::WB_Lobby_C_InputAction_Start Parms{};

	Parms.ActionName = ActionName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnChangeLevelRequest
// (BlueprintCallable, BlueprintEvent)

void UWB_Lobby_C::OnChangeLevelRequest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnChangeLevelRequest");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Lobby.WB_Lobby_C.InputAction_ChangeLevel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ActionName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::InputAction_ChangeLevel(class FName ActionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "InputAction_ChangeLevel");

	Params::WB_Lobby_C_InputAction_ChangeLevel Parms{};

	Parms.ActionName = ActionName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.InputAction_LeaveServer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ActionName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::InputAction_LeaveServer(class FName ActionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "InputAction_LeaveServer");

	Params::WB_Lobby_C_InputAction_LeaveServer Parms{};

	Parms.ActionName = ActionName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnInputTypeChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// ECommonInputType                        NewInputType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnInputTypeChanged(ECommonInputType NewInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnInputTypeChanged");

	Params::WB_Lobby_C_OnInputTypeChanged Parms{};

	Parms.NewInputType = NewInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "PreConstruct");

	Params::WB_Lobby_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnPlayerLeft
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGolfItBasePlayerState*           PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnPlayerLeft(class AGolfItBasePlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnPlayerLeft");

	Params::WB_Lobby_C_OnPlayerLeft Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnPlayerJoined
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGolfItBasePlayerState*           PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnPlayerJoined(class AGolfItBasePlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnPlayerJoined");

	Params::WB_Lobby_C_OnPlayerJoined Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.ChatMessageSent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWB_Chat_C*                       Chat                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             Message                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UWB_Lobby_C::ChatMessageSent(class UWB_Chat_C* Chat, const class FText& Message)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "ChatMessageSent");

	Params::WB_Lobby_C_ChatMessageSent Parms{};

	Parms.Chat = Chat;
	Parms.Message = std::move(Message);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnMapSelectedForChange
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGolfItBaseMapInfo*               Map_Info                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnMapSelectedForChange(class UGolfItBaseMapInfo* Map_Info)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnMapSelectedForChange");

	Params::WB_Lobby_C_OnMapSelectedForChange Parms{};

	Parms.Map_Info = Map_Info;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.LoadPracticePreview
// (BlueprintCallable, BlueprintEvent)

void UWB_Lobby_C::LoadPracticePreview()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "LoadPracticePreview");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Lobby.WB_Lobby_C.OnLocalPlayerPlayStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ELobbyPlayerPlayState                   PreviousPlayState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ELobbyPlayerPlayState                   NewPlayState                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AGolfItLobbyPlayerState*          LobbyPlayerState                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnLocalPlayerPlayStateChanged(ELobbyPlayerPlayState PreviousPlayState, ELobbyPlayerPlayState NewPlayState, const class AGolfItLobbyPlayerState* LobbyPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnLocalPlayerPlayStateChanged");

	Params::WB_Lobby_C_OnLocalPlayerPlayStateChanged Parms{};

	Parms.PreviousPlayState = PreviousPlayState;
	Parms.NewPlayState = NewPlayState;
	Parms.LobbyPlayerState = LobbyPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.Load Preview Picture
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EGolfItPlayMode                         Play_Mode                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::Load_Preview_Picture(EGolfItPlayMode Play_Mode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "Load Preview Picture");

	Params::WB_Lobby_C_Load_Preview_Picture Parms{};

	Parms.Play_Mode = Play_Mode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnPlayerNameChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           OldName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           NewName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class AGolfItLobbyPlayerState*          LobbyPlayerState                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnPlayerNameChanged(const class FString& OldName, const class FString& NewName, const class AGolfItLobbyPlayerState* LobbyPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnPlayerNameChanged");

	Params::WB_Lobby_C_OnPlayerNameChanged Parms{};

	Parms.OldName = std::move(OldName);
	Parms.NewName = std::move(NewName);
	Parms.LobbyPlayerState = LobbyPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "Tick");

	Params::WB_Lobby_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnHotseatPlayerRemoved
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGolfItLobbyPlayerState*          PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   HotSeatIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnHotseatPlayerRemoved(class AGolfItLobbyPlayerState* PlayerState, int32 HotSeatIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnHotseatPlayerRemoved");

	Params::WB_Lobby_C_OnHotseatPlayerRemoved Parms{};

	Parms.PlayerState = PlayerState;
	Parms.HotSeatIndex = HotSeatIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnPlayerTeamChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             OldTeam                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             NewTeam                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AGolfItLobbyPlayerState*          LobbyPlayerState                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnPlayerTeamChanged(class FName OldTeam, class FName NewTeam, const class AGolfItLobbyPlayerState* LobbyPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnPlayerTeamChanged");

	Params::WB_Lobby_C_OnPlayerTeamChanged Parms{};

	Parms.OldTeam = OldTeam;
	Parms.NewTeam = NewTeam;
	Parms.LobbyPlayerState = LobbyPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BindLobbySettingsEvents
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGolfItLobbySettings*             LobbySettings                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BindLobbySettingsEvents(class AGolfItLobbySettings* LobbySettings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BindLobbySettingsEvents");

	Params::WB_Lobby_C_BindLobbySettingsEvents Parms{};

	Parms.LobbySettings = LobbySettings;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnPlayModeChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EGolfItPlayMode                         NewPlayMode                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnPlayModeChanged(EGolfItPlayMode NewPlayMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnPlayModeChanged");

	Params::WB_Lobby_C_OnPlayModeChanged Parms{};

	Parms.NewPlayMode = NewPlayMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnCustomSettingsChanged
// (BlueprintCallable, BlueprintEvent)

void UWB_Lobby_C::OnCustomSettingsChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnCustomSettingsChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Lobby.WB_Lobby_C.OnGeneralSettingsChanged
// (BlueprintCallable, BlueprintEvent)

void UWB_Lobby_C::OnGeneralSettingsChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnGeneralSettingsChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Lobby.WB_Lobby_C.OnPlayerPlayStateChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ELobbyPlayerPlayState                   PreviousPlayState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ELobbyPlayerPlayState                   NewPlayState                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AGolfItLobbyPlayerState*          LobbyPlayerState                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnPlayerPlayStateChanged(ELobbyPlayerPlayState PreviousPlayState, ELobbyPlayerPlayState NewPlayState, const class AGolfItLobbyPlayerState* LobbyPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnPlayerPlayStateChanged");

	Params::WB_Lobby_C_OnPlayerPlayStateChanged Parms{};

	Parms.PreviousPlayState = PreviousPlayState;
	Parms.NewPlayState = NewPlayState;
	Parms.LobbyPlayerState = LobbyPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.ChangeSettingsWidgets
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EGolfItPlayMode                         PlayMode                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::ChangeSettingsWidgets(EGolfItPlayMode PlayMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "ChangeSettingsWidgets");

	Params::WB_Lobby_C_ChangeSettingsWidgets Parms{};

	Parms.PlayMode = PlayMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWB_Lobby_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Lobby.WB_Lobby_C.OnReadyButtonPressed
// (BlueprintCallable, BlueprintEvent)

void UWB_Lobby_C::OnReadyButtonPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnReadyButtonPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Button_ResetSettings_K2Node_ComponentBoundEvent_20_OnButtonPressed__DelegateSignature
// (BlueprintEvent)

void UWB_Lobby_C::BndEvt__WB_Lobby_Button_ResetSettings_K2Node_ComponentBoundEvent_20_OnButtonPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Button_ResetSettings_K2Node_ComponentBoundEvent_20_OnButtonPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Button_ChangeLevel_K2Node_ComponentBoundEvent_21_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Button_ChangeLevel_K2Node_ComponentBoundEvent_21_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Button_ChangeLevel_K2Node_ComponentBoundEvent_21_CommonButtonBaseClicked__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Button_ChangeLevel_K2Node_ComponentBoundEvent_21_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Button_AddFriend_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Button_AddFriend_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Button_AddFriend_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Button_AddFriend_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Button_AddHotseat_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Button_AddHotseat_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Button_AddHotseat_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Button_AddHotseat_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnAnswerReceived_ForceStart
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Answer                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::OnAnswerReceived_ForceStart(bool Answer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnAnswerReceived_ForceStart");

	Params::WB_Lobby_C_OnAnswerReceived_ForceStart Parms{};

	Parms.Answer = Answer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_MapSelection_Button_OK_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_MapSelection_Button_OK_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_MapSelection_Button_OK_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_MapSelection_Button_OK_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_MapSelection_WB_Button_Default_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_MapSelection_WB_Button_Default_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_MapSelection_WB_Button_Default_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_MapSelection_WB_Button_Default_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Auto-Scoreboard_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_AutoMinusScoreboard_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Auto-Scoreboard_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_AutoMinusScoreboard_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Bouncy_K2Node_ComponentBoundEvent_17_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_Bouncy_K2Node_ComponentBoundEvent_17_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Bouncy_K2Node_ComponentBoundEvent_17_OnSelectionChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_Bouncy_K2Node_ComponentBoundEvent_17_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Friction_K2Node_ComponentBoundEvent_16_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_Friction_K2Node_ComponentBoundEvent_16_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Friction_K2Node_ComponentBoundEvent_16_OnSelectionChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_Friction_K2Node_ComponentBoundEvent_16_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_HoleInOneOnly_K2Node_ComponentBoundEvent_15_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_HoleInOneOnly_K2Node_ComponentBoundEvent_15_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_HoleInOneOnly_K2Node_ComponentBoundEvent_15_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_HoleInOneOnly_K2Node_ComponentBoundEvent_15_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_GolfClubs_K2Node_ComponentBoundEvent_14_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_GolfClubs_K2Node_ComponentBoundEvent_14_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_GolfClubs_K2Node_ComponentBoundEvent_14_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_GolfClubs_K2Node_ComponentBoundEvent_14_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Reset_K2Node_ComponentBoundEvent_13_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_Reset_K2Node_ComponentBoundEvent_13_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Reset_K2Node_ComponentBoundEvent_13_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_Reset_K2Node_ComponentBoundEvent_13_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Penalties_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_Penalties_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Penalties_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_Penalties_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_AlternativeShooting_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_AlternativeShooting_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_AlternativeShooting_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_AlternativeShooting_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_SimulationMode_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_SimulationMode_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_SimulationMode_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_SimulationMode_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_AimArrow_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_AimArrow_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_AimArrow_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_AimArrow_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Jumping_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_Jumping_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Jumping_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_Jumping_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Collision_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_Collision_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Collision_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_Collision_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Tickrate_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ValueNormalized                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_Tickrate_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature(float Value, float ValueNormalized)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Tickrate_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_Tickrate_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;
	Parms.ValueNormalized = ValueNormalized;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Time_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ValueNormalized                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_Time_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature(float Value, float ValueNormalized)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Time_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_Time_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;
	Parms.ValueNormalized = ValueNormalized;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_PracticeHole_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ValueNormalized                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_PracticeHole_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature(float Value, float ValueNormalized)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_PracticeHole_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_PracticeHole_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;
	Parms.ValueNormalized = ValueNormalized;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Strokes_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ValueNormalized                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_Strokes_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature(float Value, float ValueNormalized)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Strokes_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_Strokes_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;
	Parms.ValueNormalized = ValueNormalized;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.BndEvt__WB_Lobby_Setting_Gamemode_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Lobby_C::BndEvt__WB_Lobby_Setting_Gamemode_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BndEvt__WB_Lobby_Setting_Gamemode_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature");

	Params::WB_Lobby_C_BndEvt__WB_Lobby_Setting_Gamemode_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.mOnDone_FE6A5E0D4DFCF970667F04B1BE9F87C4
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Context                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USaveGame*                        SaveGame                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::MOnDone_FE6A5E0D4DFCF970667F04B1BE9F87C4(class UObject* Context, class USaveGame* SaveGame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "mOnDone_FE6A5E0D4DFCF970667F04B1BE9F87C4");

	Params::WB_Lobby_C_MOnDone_FE6A5E0D4DFCF970667F04B1BE9F87C4 Parms{};

	Parms.Context = Context;
	Parms.SaveGame = SaveGame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.OnLoaded_9B9B5A714F8998987481F5B8DF60A0BC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::OnLoaded_9B9B5A714F8998987481F5B8DF60A0BC(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnLoaded_9B9B5A714F8998987481F5B8DF60A0BC");

	Params::WB_Lobby_C_OnLoaded_9B9B5A714F8998987481F5B8DF60A0BC Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.mOnDone_49189E364B96BB0BECF5B2B660FFEB6E
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Context                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture2D*                       PreviewPicture                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::MOnDone_49189E364B96BB0BECF5B2B660FFEB6E(class UObject* Context, class UTexture2D* PreviewPicture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "mOnDone_49189E364B96BB0BECF5B2B660FFEB6E");

	Params::WB_Lobby_C_MOnDone_49189E364B96BB0BECF5B2B660FFEB6E Parms{};

	Parms.Context = Context;
	Parms.PreviewPicture = PreviewPicture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.CreateTeam
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Param_Name                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWB_Lobby_Team_C*                 Team_Widget                                            (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::CreateTeam(class FName Param_Name, class UWB_Lobby_Team_C** Team_Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "CreateTeam");

	Params::WB_Lobby_C_CreateTeam Parms{};

	Parms.Param_Name = Param_Name;

	UObject::ProcessEvent(Func, &Parms);

	if (Team_Widget != nullptr)
		*Team_Widget = Parms.Team_Widget;
}


// Function WB_Lobby.WB_Lobby_C.RemoveTeam
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Param_Name                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::RemoveTeam(class FName Param_Name)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "RemoveTeam");

	Params::WB_Lobby_C_RemoveTeam Parms{};

	Parms.Param_Name = Param_Name;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.ClearTeams
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Lobby_C::ClearTeams()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "ClearTeams");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Lobby.WB_Lobby_C.AddPlayer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGolfItLobbyPlayerState*          PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Team                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   HotSeatIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsKickable                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::AddPlayer(class AGolfItLobbyPlayerState* PlayerState, class FName Team, int32 HotSeatIndex, bool IsKickable, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "AddPlayer");

	Params::WB_Lobby_C_AddPlayer Parms{};

	Parms.PlayerState = PlayerState;
	Parms.Team = Team;
	Parms.HotSeatIndex = HotSeatIndex;
	Parms.IsKickable = IsKickable;

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function WB_Lobby.WB_Lobby_C.RemovePlayer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGolfItLobbyPlayerState*          PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Team                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   HotSeatIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::RemovePlayer(class AGolfItLobbyPlayerState* PlayerState, class FName Team, int32 HotSeatIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "RemovePlayer");

	Params::WB_Lobby_C_RemovePlayer Parms{};

	Parms.PlayerState = PlayerState;
	Parms.Team = Team;
	Parms.HotSeatIndex = HotSeatIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.ApplyGeneralSettings
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGolfItLobbySettings*             Settings                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::ApplyGeneralSettings(class AGolfItLobbySettings* Settings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "ApplyGeneralSettings");

	Params::WB_Lobby_C_ApplyGeneralSettings Parms{};

	Parms.Settings = Settings;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.ApplyCustomSettings
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGolfItLobbySettings*             Settings                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::ApplyCustomSettings(class AGolfItLobbySettings* Settings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "ApplyCustomSettings");

	Params::WB_Lobby_C_ApplyCustomSettings Parms{};

	Parms.Settings = Settings;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.TryJoinTeam
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Team                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::TryJoinTeam(class FName Team)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "TryJoinTeam");

	Params::WB_Lobby_C_TryJoinTeam Parms{};

	Parms.Team = Team;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Lobby.WB_Lobby_C.PlayStateToButtonState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ELobbyPlayerPlayState                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_Button_States                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

E_Button_States UWB_Lobby_C::PlayStateToButtonState(ELobbyPlayerPlayState Param_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "PlayStateToButtonState");

	Params::WB_Lobby_C_PlayStateToButtonState Parms{};

	Parms.Param_Index = Param_Index;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_Lobby.WB_Lobby_C.FindPracticePreview
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   Hole                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TSoftObjectPtr<class UTexture2D>        Preview                                                (Parm, OutParm, HasGetValueTypeHash)

void UWB_Lobby_C::FindPracticePreview(const class FString& Level, int32 Hole, TSoftObjectPtr<class UTexture2D>* Preview)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "FindPracticePreview");

	Params::WB_Lobby_C_FindPracticePreview Parms{};

	Parms.Level = std::move(Level);
	Parms.Hole = Hole;

	UObject::ProcessEvent(Func, &Parms);

	if (Preview != nullptr)
		*Preview = Parms.Preview;
}


// Function WB_Lobby.WB_Lobby_C.ApplyRecommendedSettings
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGolfItLobbySettings*             LobbySettings                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    AppliedSettings                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Lobby_C::ApplyRecommendedSettings(class AGolfItLobbySettings* LobbySettings, bool* AppliedSettings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "ApplyRecommendedSettings");

	Params::WB_Lobby_C_ApplyRecommendedSettings Parms{};

	Parms.LobbySettings = LobbySettings;

	UObject::ProcessEvent(Func, &Parms);

	if (AppliedSettings != nullptr)
		*AppliedSettings = Parms.AppliedSettings;
}


// Function WB_Lobby.WB_Lobby_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FKeyEvent                        InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWB_Lobby_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "OnKeyDown");

	Params::WB_Lobby_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_Lobby.WB_Lobby_C.ResetHotseatIDs
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWB_Lobby_C::ResetHotseatIDs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "ResetHotseatIDs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Lobby.WB_Lobby_C.GetHotseatName
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             Param_Name                                             (Parm, OutParm)

void UWB_Lobby_C::GetHotseatName(class FText* Param_Name)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "GetHotseatName");

	Params::WB_Lobby_C_GetHotseatName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Name != nullptr)
		*Param_Name = std::move(Parms.Param_Name);
}


// Function WB_Lobby.WB_Lobby_C.BP_OnHandleBackAction
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWB_Lobby_C::BP_OnHandleBackAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BP_OnHandleBackAction");

	Params::WB_Lobby_C_BP_OnHandleBackAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_Lobby.WB_Lobby_C.CustomNavigationCustomMode
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Param_Navigation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWB_Lobby_C::CustomNavigationCustomMode(EUINavigation Param_Navigation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "CustomNavigationCustomMode");

	Params::WB_Lobby_C_CustomNavigationCustomMode Parms{};

	Parms.Param_Navigation = Param_Navigation;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_Lobby.WB_Lobby_C.DoCustomNavigation_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Param_Navigation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWB_Lobby_C::DoCustomNavigation_0(EUINavigation Param_Navigation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "DoCustomNavigation_0");

	Params::WB_Lobby_C_DoCustomNavigation_0 Parms{};

	Parms.Param_Navigation = Param_Navigation;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_Lobby.WB_Lobby_C.CustomNavigationResetButton
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Param_Navigation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWB_Lobby_C::CustomNavigationResetButton(EUINavigation Param_Navigation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "CustomNavigationResetButton");

	Params::WB_Lobby_C_CustomNavigationResetButton Parms{};

	Parms.Param_Navigation = Param_Navigation;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_Lobby.WB_Lobby_C.ResetFrictionAndBounce
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Lobby_C::ResetFrictionAndBounce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "ResetFrictionAndBounce");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Lobby.WB_Lobby_C.MakeSpaceInTextFromUpperCase
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString                           Input                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           Output                                                 (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Lobby_C::MakeSpaceInTextFromUpperCase(const class FString& Input, class FString* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "MakeSpaceInTextFromUpperCase");

	Params::WB_Lobby_C_MakeSpaceInTextFromUpperCase Parms{};

	Parms.Input = std::move(Input);

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = std::move(Parms.Output);
}


// Function WB_Lobby.WB_Lobby_C.GetDefaultTeam
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FName                             DefaultTeam                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Lobby_C::GetDefaultTeam(class FName* DefaultTeam) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "GetDefaultTeam");

	Params::WB_Lobby_C_GetDefaultTeam Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DefaultTeam != nullptr)
		*DefaultTeam = Parms.DefaultTeam;
}


// Function WB_Lobby.WB_Lobby_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWB_Lobby_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Lobby_C", "BP_GetDesiredFocusTarget");

	Params::WB_Lobby_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

