#pragma once

/*
* SDK generated by Dumper-7 ~ https://github.com/Encryqed/Dumper-7
*
* [Modified by OriginSoftware] ~ https://github.com/Wimberton/OriginPalia
*/

// Package: WB_Options_General

#include "Basic.hpp"

#include "WB_Options_General_classes.hpp"
#include "WB_Options_General_parameters.hpp"


namespace SDK
{

// Function WB_Options_General.WB_Options_General_C.BndEvt__WB_Options_General_Checkbox_HideNotifications_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Options_General_C::BndEvt__WB_Options_General_Checkbox_HideNotifications_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BndEvt__WB_Options_General_Checkbox_HideNotifications_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature");

	Params::WB_Options_General_C_BndEvt__WB_Options_General_Checkbox_HideNotifications_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.BndEvt__WB_Options_General_Dropbox_PutterVisibility_K2Node_ComponentBoundEvent_3_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Options_General_C::BndEvt__WB_Options_General_Dropbox_PutterVisibility_K2Node_ComponentBoundEvent_3_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BndEvt__WB_Options_General_Dropbox_PutterVisibility_K2Node_ComponentBoundEvent_3_OnSelectionChanged__DelegateSignature");

	Params::WB_Options_General_C_BndEvt__WB_Options_General_Dropbox_PutterVisibility_K2Node_ComponentBoundEvent_3_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.BndEvt__WB_Options_General_Dropbox_GoalVisibility_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Options_General_C::BndEvt__WB_Options_General_Dropbox_GoalVisibility_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BndEvt__WB_Options_General_Dropbox_GoalVisibility_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature");

	Params::WB_Options_General_C_BndEvt__WB_Options_General_Dropbox_GoalVisibility_K2Node_ComponentBoundEvent_5_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.ExecuteUbergraph_WB_Options_General
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Options_General_C::ExecuteUbergraph_WB_Options_General(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "ExecuteUbergraph_WB_Options_General");

	Params::WB_Options_General_C_ExecuteUbergraph_WB_Options_General Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.SetBusVolume
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Volume                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TSoftObjectPtr<class UFMODBus>          Bus                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWB_Options_General_C::SetBusVolume(float Volume, TSoftObjectPtr<class UFMODBus> Bus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "SetBusVolume");

	Params::WB_Options_General_C_SetBusVolume Parms{};

	Parms.Volume = Volume;
	Parms.Bus = Bus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.HideOrShowResolution
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_Options_General_C::HideOrShowResolution()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "HideOrShowResolution");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Options_General.WB_Options_General_C.SetupResolutions
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWB_Options_General_C::SetupResolutions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "SetupResolutions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Options_General.WB_Options_General_C.SortResolutions
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FIntPoint>                Input                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<struct FIntPoint>                Output                                                 (Parm, OutParm)

void UWB_Options_General_C::SortResolutions(TArray<struct FIntPoint>& Input, TArray<struct FIntPoint>* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "SortResolutions");

	Params::WB_Options_General_C_SortResolutions Parms{};

	Parms.Input = std::move(Input);

	UObject::ProcessEvent(Func, &Parms);

	Input = std::move(Parms.Input);

	if (Output != nullptr)
		*Output = std::move(Parms.Output);
}


// Function WB_Options_General.WB_Options_General_C.StringToResolution
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString                           String                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FIntPoint                        Resolution                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Options_General_C::StringToResolution(const class FString& String, struct FIntPoint* Resolution)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "StringToResolution");

	Params::WB_Options_General_C_StringToResolution Parms{};

	Parms.String = std::move(String);

	UObject::ProcessEvent(Func, &Parms);

	if (Resolution != nullptr)
		*Resolution = std::move(Parms.Resolution);
}


// Function WB_Options_General.WB_Options_General_C.ResolutionToString
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FIntPoint                        Resolution                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           String                                                 (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Options_General_C::ResolutionToString(const struct FIntPoint& Resolution, class FString* String)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "ResolutionToString");

	Params::WB_Options_General_C_ResolutionToString Parms{};

	Parms.Resolution = std::move(Resolution);

	UObject::ProcessEvent(Func, &Parms);

	if (String != nullptr)
		*String = std::move(Parms.String);
}


// Function WB_Options_General.WB_Options_General_C.GetResolutions
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FIntPoint>                Param_Resolutions                                      (Parm, OutParm)
// bool                                    Successful                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Options_General_C::GetResolutions(TArray<struct FIntPoint>* Param_Resolutions, bool* Successful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "GetResolutions");

	Params::WB_Options_General_C_GetResolutions Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Resolutions != nullptr)
		*Param_Resolutions = std::move(Parms.Param_Resolutions);

	if (Successful != nullptr)
		*Successful = Parms.Successful;
}


// Function WB_Options_General.WB_Options_General_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWB_Options_General_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Options_General.WB_Options_General_C.BndEvt__WB_Options_General_Dropdown_Resolution_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Options_General_C::BndEvt__WB_Options_General_Dropdown_Resolution_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BndEvt__WB_Options_General_Dropdown_Resolution_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature");

	Params::WB_Options_General_C_BndEvt__WB_Options_General_Dropdown_Resolution_K2Node_ComponentBoundEvent_0_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.BndEvt__WB_Options_General_Checkbox_ChatFilter_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Options_General_C::BndEvt__WB_Options_General_Checkbox_ChatFilter_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BndEvt__WB_Options_General_Checkbox_ChatFilter_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature");

	Params::WB_Options_General_C_BndEvt__WB_Options_General_Checkbox_ChatFilter_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.BndEvt__WB_Options_Advanced_Dropbox_TrailSettings_K2Node_ComponentBoundEvent_1_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Options_General_C::BndEvt__WB_Options_Advanced_Dropbox_TrailSettings_K2Node_ComponentBoundEvent_1_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BndEvt__WB_Options_Advanced_Dropbox_TrailSettings_K2Node_ComponentBoundEvent_1_OnSelectionChanged__DelegateSignature");

	Params::WB_Options_General_C_BndEvt__WB_Options_Advanced_Dropbox_TrailSettings_K2Node_ComponentBoundEvent_1_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.BndEvt__WB_Options_General_Dropdown_Language_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Options_General_C::BndEvt__WB_Options_General_Dropdown_Language_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BndEvt__WB_Options_General_Dropdown_Language_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature");

	Params::WB_Options_General_C_BndEvt__WB_Options_General_Dropdown_Language_K2Node_ComponentBoundEvent_7_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.BndEvt__WB_Options_General_Dropdown_Fullscreen_K2Node_ComponentBoundEvent_8_OnSelectionChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWB_Options_General_C::BndEvt__WB_Options_General_Dropdown_Fullscreen_K2Node_ComponentBoundEvent_8_OnSelectionChanged__DelegateSignature(const class FString& Option)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BndEvt__WB_Options_General_Dropdown_Fullscreen_K2Node_ComponentBoundEvent_8_OnSelectionChanged__DelegateSignature");

	Params::WB_Options_General_C_BndEvt__WB_Options_General_Dropdown_Fullscreen_K2Node_ComponentBoundEvent_8_OnSelectionChanged__DelegateSignature Parms{};

	Parms.Option = std::move(Option);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.BndEvt__WB_Options_General_Checkbox_AlwaysShowChallenge_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWB_Options_General_C::BndEvt__WB_Options_General_Checkbox_AlwaysShowChallenge_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BndEvt__WB_Options_General_Checkbox_AlwaysShowChallenge_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature");

	Params::WB_Options_General_C_BndEvt__WB_Options_General_Checkbox_AlwaysShowChallenge_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Options_General.WB_Options_General_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWB_Options_General_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Options_General_C", "BP_GetDesiredFocusTarget");

	Params::WB_Options_General_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

